:PROPERTIES:
#+INCLUDE: "./macros.org"
#+TITLE: {{{SITETITLE}}}
#+AUTHOR: Spencer A. Hill
#+EMAIL: spencerh@princeton.edu
#+DATE:
#+DESCRIPTION: Spencer Hill's academic website
#+KEYWORDS:
#+OPTIONS: toc:nil ':nil
#+LANGUAGE: en
#+HTML: <link rel="stylesheet" type="text/css" href="style.css?v=3">
{{{NAVBAR}}}
:END:
* Overview
Welcome!  I am a climate scientist interested in tropical overturning
circulations ([[https://en.wikipedia.org/wiki/Monsoon][monsoons]], [[https://en.wikipedia.org/wiki/Hadley_cell][Hadley cells]], and the [[https://en.wikipedia.org/wiki/Intertropical_Convergence_Zone][Intertropical Convergence Zone]]
a.k.a. the ITCZ).  Specifically:

- Why they exist when and where they do
- How they ebb and flow over the course of each year
- How well we can predict their variations from year to year
- How those year-to-year variations affect agricultural and economic outcomes
- How they may have changed in Earth's history
- How they may change in Earth's future
- How they behave in other planetary atmospheres.

I'm also interested in how weather and climate impact real-world outcomes for
New York City.  I explore all this with the other talented members of my New
York Climate Investigations: Theory To Impacts (New York CITTI) research group.
Please see the [[file:publications.org][Publications]] page to learn more about our past work, the [[file:group.org][Group]]
page to learn more about who we are, and the [[file:opportunities.org][Opportunities]] page to learn more
about joining us.

I work in the [[https://www.ccny.cuny.edu/eas][Department of Earth and Atmospheric
Sciences]] at [[https://www.ccny.cuny.edu/][The City College of New York]] as an Assistant Professor.

I also hold an adjunct position at the [[https://www.ldeo.columbia.edu/][Lamont-Doherty Earth
Observatory]] at [[https://www.columbia.edu/][Columbia University]], where I collaborate with [[https://www.ldeo.columbia.edu/~biasutti/][Michela
Biasutti]] on a project investigating the role of energy transports by tropical
transient disturbances in setting the location of the ITCZ.

I am also interested in the connections between weather and climate
science on the one hand with music, literature, poetry, and other forms of human
expression on the other hand.  I write about this at my blog, [[https://spencerahill.github.io/couldnt-stand-the-weather/home.html][Couldn't Stand the
Weather]], and occasionally tweet about it from my account [[https://twitter.com/spencerahill][@spencerahill]]
using the hashtag [[https://twitter.com/hashtag/CliSciHiFi][#CliSciHiFi]].

I also co-founded the "[[https://diynamics.github.io/][DIYnamics]]" project that seeks to improve the teaching of
meteorology, climate science, and other planetary-scale sciences at the K-12
through graduate school levels by developing inexpensive, easy-to-use kits for
performing physical demonstrations of core scientific concepts.  Please the
DIYnamics [[https://diynamics.github.io/][website]] and [[https://www.youtube.com/channel/UCnUHxOSVY4G4OFbF8XL1qUg][YouTube]] channel for more.

Finally, I am also interested in developing software tools for scientists in the Python
programming language.  Please see my [[file:resources.org][Resources]] page for more.

Please contact me (information below) with any questions about my research or
anything else you find on this site.  Thanks!
#+HTML: <hr/>
* Contact
[[mailto:shill1@ccny.cuny.edu][shill1@ccny.cuny.edu]] | Room 733 | Marshak Science Building | The City College of
New York | 160 Convent Avenue | New York, NY 10031
