:PROPERTIES:
#+INCLUDE: "macros.org"
#+TITLE: {{{SITETITLE}}}
{{{NAVBAR}}}
{{{PAGETITLE(Opportunities)}}}
:END:

I am always looking for talented students and early-career scientists to join
the NYCITTI research group at CCNY.  While the funds and other resources I have
available for specific projects changes with time, don't hesitate to contact me
anytime if you're interested in working with me.  Read on for more
information.
#+HTML: <hr/>
* Undergraduate students
For current or incoming *undergraduates* at CCNY, research positions could be
for course credit or not.  Summer research internships are also available.  Just
email me or swing by my office sometime.
#+HTML: <hr/>
* Master's students
Students interested in pursuing a Master's Degree with me should check out the CCNY
Earth and Atmospheric Sciences [[https://easgrad.ccnysites.cuny.edu/][M.S. program]].  Applications are reviewed on a
rolling basis, but they should be submitted by *May 1st* for a Fall term start
or by *November 15th* for a Spring term start.
#+HTML: <hr/>
* Ph.D. students
I advise Ph.D. students through the [[https://www.gc.cuny.edu/earth-and-environmental-sciences][Dept. of Earth and Environmental Sciences]]
(EES) and the [[https://www.gc.cuny.edu/physics][Dept. of Physics]] at the [[https://www.gc.cuny.edu/][City University of New York Graduate
Center]] (GC).

*For enrollment starting the subsequent fall, the annual deadline for the GC EES Ph.D. program is mid-December.*

*For enrollment starting the subsequent fall, the deadline for GC Physics is early January.*

Please reach out to me well in advance if you are interested in applying.

It is especially useful to hear from prospective students well in advance of the
[[https://www.nsfgrfp.org/][NSF Graduate Research Fellowship]] (GRFP) program annual deadline in mid/late
October, so that there's the possibility of working together on that.  But
that's not the only possible funding source, and even if you're past any of these
deadlines, please email me to see what can be arranged. 
#+HTML: <hr/>
* Postdocs
Postdocs are hired through the CCNY EAS Department.  If you have a Ph.D. or will
have one soon and are interested in working with me, please email!  If I don't
have funding on hand for a position, we can potentially work together to prepare
a postdoctoral fellowship application.  
